#!/usr/bin/env python3
import sys

try:
    from netlink import launcher
except ImportError:
    print("ERROR: Failed to import NetLink launcher module (netlink.launcher).\n\nIf you are "
          "running NetLink from source, please install NetLink first using 'python3 "
          "setup.py install' (global install) or 'python3 setup.py install --user'"
          " (local install)\n")
    sys.exit(1)
else:
    if __name__ == '__main__':
        launcher.main()
