"""Build hook for PyLink IRC Services.

Project metadata now lives in pyproject.toml (PEP 621). This module remains only
to generate the version file (__init__.py) with the git-described build version,
which is read at runtime by the launcher.
"""

import subprocess
import sys

if sys.version_info < (3, 9):
    raise RuntimeError("PyLink requires Python 3.9 or higher.")

from setuptools import setup

with open('VERSION', encoding='utf-8') as f:
    version = f.read().strip()

# Try to fetch the current commit hash from Git for the runtime "real" version.
try:
    real_version = subprocess.check_output(['git', 'describe', '--tags']).decode('utf-8').strip()
except Exception as e:
    print('WARNING: Failed to get Git version from "git describe --tags": %s: %s' % (type(e).__name__, e))
    print("If you're installing from PyPI or a tarball, ignore the above message.")
    real_version = version + '-nogit'

with open('__init__.py', 'w') as f:
    f.write('# Automatically generated by setup.py\n')
    f.write('__version__ = %r\n' % version)
    f.write('real_version = %r\n' % real_version)

setup()
